// <copyright file="Achievements.cs" company="Jan Ivar Z. Carlsen, Sindri Jóelsson">
// Copyright (c) 2016 Jan Ivar Z. Carlsen, Sindri Jóelsson. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>

namespace CloudOnce
{
    using System.Collections.Generic;
    using Internal;

    /// <summary>
    /// Provides access to achievements registered via the CloudOnce Editor.
    /// This file was automatically generated by CloudOnce. Do not edit.
    /// </summary>
    public static class Achievements
    {
        private static readonly UnifiedAchievement s_scoreMaster = new UnifiedAchievement("scoreMaster",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIuvz0_NcCEAIQBw"
#else
            "scoreMaster"
#endif
            );

        public static UnifiedAchievement scoreMaster
        {
            get { return s_scoreMaster; }
        }

        private static readonly UnifiedAchievement s_speedster = new UnifiedAchievement("speedster",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIuvz0_NcCEAIQCA"
#else
            "speedster"
#endif
            );

        public static UnifiedAchievement speedster
        {
            get { return s_speedster; }
        }

        private static readonly UnifiedAchievement s_comboGod = new UnifiedAchievement("comboGod",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIuvz0_NcCEAIQCQ"
#else
            "comboGod"
#endif
            );

        public static UnifiedAchievement comboGod
        {
            get { return s_comboGod; }
        }

        private static readonly UnifiedAchievement s_mountEverest = new UnifiedAchievement("mountEverest",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIuvz0_NcCEAIQCg"
#else
            "mountEverest"
#endif
            );

        public static UnifiedAchievement mountEverest
        {
            get { return s_mountEverest; }
        }

        private static readonly UnifiedAchievement s_millionaire = new UnifiedAchievement("millionaire",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIuvz0_NcCEAIQCw"
#else
            "millionaire"
#endif
            );

        public static UnifiedAchievement millionaire
        {
            get { return s_millionaire; }
        }

        private static readonly UnifiedAchievement s_destroyer = new UnifiedAchievement("destroyer",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIuvz0_NcCEAIQDA"
#else
            "destroyer"
#endif
            );

        public static UnifiedAchievement destroyer
        {
            get { return s_destroyer; }
        }

        private static readonly UnifiedAchievement s_andromeda = new UnifiedAchievement("andromeda",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIuvz0_NcCEAIQDQ"
#else
            "andromeda"
#endif
            );

        public static UnifiedAchievement andromeda
        {
            get { return s_andromeda; }
        }

        private static readonly UnifiedAchievement s_triangulum = new UnifiedAchievement("triangulum",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIuvz0_NcCEAIQDg"
#else
            "triangulum"
#endif
            );

        public static UnifiedAchievement triangulum
        {
            get { return s_triangulum; }
        }

        private static readonly UnifiedAchievement s_prestidge = new UnifiedAchievement("prestidge",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIuvz0_NcCEAIQDw"
#else
            "prestidge"
#endif
            );

        public static UnifiedAchievement prestidge
        {
            get { return s_prestidge; }
        }

        public static readonly UnifiedAchievement[] All =
        {
            s_scoreMaster,
            s_speedster,
            s_comboGod,
            s_mountEverest,
            s_millionaire,
            s_destroyer,
            s_andromeda,
            s_triangulum,
            s_prestidge,
        };

        public static string GetPlatformID(string internalId)
        {
            return s_achievementDictionary.ContainsKey(internalId)
                ? s_achievementDictionary[internalId].ID
                : string.Empty;
        }

        private static readonly Dictionary<string, UnifiedAchievement> s_achievementDictionary = new Dictionary<string, UnifiedAchievement>
        {
            { "scoreMaster", s_scoreMaster },
            { "speedster", s_speedster },
            { "comboGod", s_comboGod },
            { "mountEverest", s_mountEverest },
            { "millionaire", s_millionaire },
            { "destroyer", s_destroyer },
            { "andromeda", s_andromeda },
            { "triangulum", s_triangulum },
            { "prestidge", s_prestidge },
        };
    }
}
